import { Logger } from '@nestjs/common';
import { HttpAdapterHost, NestFactory } from '@nestjs/core';
import { SwaggerModule } from '@nestjs/swagger';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { PrismaClientExceptionFilter } from 'nestjs-prisma';
import { AppModule } from './app/app.module';
import * as fs from 'fs';
import * as path from 'path';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );

  // Read the Swagger JSON file generated by Nestia
  const swaggerPath = path.join(
    __dirname,
    '../../../apps/backend/docs/swagger.json',
  );
  const swaggerDocument = JSON.parse(fs.readFileSync(swaggerPath, 'utf-8'));

  SwaggerModule.setup('docs', app, swaggerDocument);

  const globalPrefix = 'api';
  app.setGlobalPrefix(globalPrefix);

  const { httpAdapter } = app.get(HttpAdapterHost);
  app.useGlobalFilters(new PrismaClientExceptionFilter(httpAdapter));

  const port = process.env.PORT || 3000;
  await app.listen(port);

  Logger.log(
    `🚀 Application is running on: http://localhost:${port}/${globalPrefix}`,
  );
}

bootstrap();
