import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import CategoryMenu from '../components/CategoryMenu';
import HeaderDesktop from '../components/HeaderDesktop';
import Footer from '../components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderDesktop />
        <CategoryMenu />
        <main className="layout-w">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
